name: gh-pages

on:
  push:
    branches: [main]

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Build
        run: |
          npm ci
          npm run build:pages

      - uses: peaceiris/actions-gh-pages@v3
        with:
          enable_jekyll: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./preview
          user_email: "github-actions[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
